### ISSUE TITLE
Test the examples and check the results

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#149]
We really should create a meta example that starts the examples and check the results before we release. That would make things much easier and more stable. An output could be like this:

```
storage_example:
    run: okay
    results: okay

another_example:
    run: okay
    results: failed

another_example2:
    run: failed
    results: empty

See logfile for more information.
```
